CREATE DATABASE districolor_db;

USE districolor_db

CREATE TABLE ARTICULOS 
(
codigo_art INT IDENTITY(1,1) NOT NULL,
nombre_art VARCHAR(255) NOT NULL,
precio_art NUMERIC(8,2) NOT NULL
CONSTRAINT pk_articulo PRIMARY KEY (codigo_art)
);

CREATE TABLE FORMAS_PAGO 
(
codigo_formapago INT IDENTITY(1,1) NOT NULL,
nombre_formapago VARCHAR(255) NOT NULL,
CONSTRAINT pk_formapago PRIMARY KEY (codigo_formapago)
);

CREATE TABLE FACTURAS
(
numero_fac INT IDENTITY(1,1) NOT NULL,
fecha_fac DATE NOT NULL,
codigo_formapago INT NOT NULL,
cliente VARCHAR(255) NOT NULL
CONSTRAINT pk_factura PRIMARY KEY (numero_fac)
CONSTRAINT fk_factura_formapago FOREIGN KEY (codigo_formapago) REFERENCES FORMAS_PAGO (codigo_formapago)
);

CREATE TABLE DETALLES_FACTURA
(
numero_fac INT NOT NULL,
numero_detalle INT NOT NULL,
codigo_art INT NOT NULL,
cantidad INT NOT NULL
CONSTRAINT pk_detalle_factura PRIMARY KEY (numero_fac, numero_detalle)
CONSTRAINT fk_detalle_factura_factura FOREIGN KEY (numero_fac) REFERENCES FACTURAS (numero_fac),
CONSTRAINT fk_detalle_factura_articulo FOREIGN KEY (codigo_art) REFERENCES ARTICULOS (codigo_art)
);

INSERT INTO ARTICULOS VALUES('TONER HP Q2612A 12A',8500);
INSERT INTO ARTICULOS VALUES('TONER HP CB435A CE285A 35A/85A',8900);
INSERT INTO ARTICULOS VALUES('TONER HP CE278A 78A',8900);
INSERT INTO ARTICULOS VALUES('TONER HP CF283A 83A',8900);
INSERT INTO ARTICULOS VALUES('TONER HP CF258A 58A',15600);

INSERT INTO FORMAS_PAGO VALUES('EFECTIVO');
INSERT INTO FORMAS_PAGO VALUES('TARJETA DE DEBITO');
INSERT INTO FORMAS_PAGO VALUES('TARJETA DE CREDITO');
INSERT INTO FORMAS_PAGO VALUES('TRANSFERENCIA BANCARIA');
INSERT INTO FORMAS_PAGO VALUES('CHEQUE CPD');